#!/usr/bin/env bash
nix fmt
git diff -U0 '*.nix'
echo "rebuilding nixos..."
sudo nixos-rebuild switch --flake "$HOME/nixos#zero" | tee rebuild.log || ( grep rebuild.log --color error && exit 1)
notify-send -e "nixos rebuilt OK!"