#!/usr/bin/env bash
# usage: ~/nixos/switch <home | os> <user | system>

set -e
pushd ~/nixos || exit

if [ -z "$1" ] || [ -z "$2" ]; then 
   echo "usage: switch <home | os> <user | system>"
   popd
   exit 0
fi

# autoformat
nix fmt &>/dev/null \
   || (nix fmt ; echo "formatting failed!" && exit 1)

# shows changes
git diff -U0 '*.nix'

if [ "$1" = "home" ]; then
   echo "rebuilding home-manager for user $2..."
   rm -rf ~/.config/gtk-4.0/gtk.css # Hack! This should be backing up, but it isn't?
   home-manager switch --flake "$HOME/nixos#$2" -b backup | tee switch.log || ( grep rebuild.log --color error && exit 1)
   notify-send -e "home manager rebuilt!"
elif [ "$1" = "os" ]; then
   echo "rebuilding nixos for host $2..."
   sudo nixos-rebuild switch --flake "$HOME/nixos#$2" | tee switch.log || ( grep rebuild.log --color error && exit 1)
   notify-send -e "nixos rebuilt!"
fi

popd || echo "failed to popd"
